src/main/java/com/example/hr/models/Employee.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.hr.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
public class Employee {

    private int ID;
    private String firstName;
    private String lastName;
    private String division;
    private String building;
    private String title;
    private String room;
}

src/main/java/com/example/hr/models/SearchCriteria.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.hr.models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SearchCriteria {
    private String fieldName;
    private String searchKey;
}

src/main/java/com/example/hr/employee/EmployeeBean.java
package com.example.hr.employee;

import com.example.hr.models.Employee;
import com.example.hr.service.HRService;
import lombok.Setter;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.List;
import lombok.Getter;

@ManagedBean(name = "employee", eager = true)
@SessionScoped
public class EmployeeBean {

    private HRService hrService;
    
    private int searchId;

    public int getSearchId() {
        return searchId;
    }

    public void setSearchId(int searchId) {
        this.searchId = searchId;
    }

    public void setHrService(HRService hrService) {
        this.hrService = hrService;
    }

    public List<Employee> getAllEmployee() {
        return hrService.getAllEmployee();
    }

    public void getEmployeeSearch() {
        System.out.println("getEmployeeSearch");
    }

    public void getPrint() {
        System.out.println("Method");
    }
}

src/main/resources/webapp/home.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">
   <head>
      <title>JSF Tutorial! WEB-App</title>
   </head>

   <body>
      #{helloWorld.message()}
   </body>
</html>

src/main/webapp/employeeRead.xhtml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml"
      xmlns:f = "http://java.sun.com/jsf/core"
      xmlns:h = "http://java.sun.com/jsf/html">

    <h:head>
        <title>HR Leads!</title>
        <h:outputStylesheet library = "css" name = "styles.css"  /> 
    </h:head>

    <h:body>
        <h2>HR Employee Search.</h2>
        <h:form>
            <h3>Search Employee</h3>
            <hr />
            <table>
                <tr>
                    <td>ID:</td>
                    <td><h:inputText size="15" value="#{employee.searchId}" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td><h:commandButton value="Search Employee"
                                         action="#{employee.employeeSearch}" /></td>
                </tr>
            </table>
        </h:form>


        <h2>HR Leads Example</h2>

        <h:dataTable value = "#{employee.allEmployee}" var = "emp"
                     styleClass = "authorTable"
                     headerClass = "authorTableHeader"
                     rowClasses = "authorTableOddRow,authorTableEvenRow">

            <h:column><f:facet name = "header">Employee ID</f:facet>
                    #{emp.ID}
            </h:column>
            <h:column><f:facet name = "header">First Name</f:facet>
                    #{emp.firstName}
            </h:column>
            <h:column><f:facet name = "header">Last Name</f:facet>
                    #{emp.lastName}
            </h:column>
            <h:column><f:facet name = "header">Division</f:facet>
                    #{emp.division}
            </h:column>
            <h:column><f:facet name = "header">Building</f:facet>
                    #{emp.building}
            </h:column>
            <h:column><f:facet name = "header">Title</f:facet>
                    #{emp.title}
            </h:column>
            <h:column><f:facet name = "header">Room</f:facet>
                    #{emp.room}
            </h:column>
        </h:dataTable>
    </h:body>

</html>

src/main/webapp/employeeSearch.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Employee Search</title>
    </h:head>
    <h:body>
        <h2>HR Employee Search.</h2>
        <h:form>
            <h3>Search Employee</h3>
            <hr />
            <table>
                <tr>
                    <td>ID:</td>
                    <td><h:inputText size="15" value="#{employee.searchId}" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td><h:commandButton value="Search Employee"
                                         action="#{employee.employeeSearch}" /></td>
                </tr>
            </table>

        </h:form>
    </h:body>

</html>